/*
 * plugindefinitions.h
 *
 *  Created on: 11/01/2010
 *      Author: ivocalado
 */

#ifndef PLUGINDEFINITIONS_H_
#define PLUGINDEFINITIONS_H_

enum MessageType {
	__INVALID_OPTION,
//Main options
	__ENCODER_OPT,
	__DECODER_OPT,
	__PREPROCESS_OPT,
//Secondary options
	__SPEEX_ENH,
	__SPEEX_FRAME_SIZE,
	__SPEEX_QUALITY,
	__SPEEX_MODE,
	__SPEEX_VBR,
	__SPEEX_VBR_QUALITY,
	__SPEEX_COMPLEXITY,
	__SPEEX_BITRATE,
	__SPEEX_SAMPLING_RATE,
	__SPEEX_RESET_STATE,
	__SPEEX_VAD,
	__SPEEX_DTX,
	__SPEEX_ABR,
	__SPEEX_PLC_TUNING,
	__SPEEX_VBR_MAX_BITRATE,
	__SPEEX_HIGHPASS,

	/*Preprocessing options */
	__SPEEX_PREPROCESS_DENOISE,
	__SPEEX_PREPROCESS_AGC,
	__SPEEX_PREPROCESS_AGC_LEVEL,
	__SPEEX_PREPROCESS_DEREVERB,
	__SPEEX_PREPROCESS_DEREVERB_LEVEL,
	__SPEEX_PREPROCESS_DEREVERB_DECAY,
	__SPEEX_PREPROCESS_PROB_START,
	__SPEEX_PREPROCESS_PROB_CONTINUE,
	__SPEEX_PREPROCESS_NOISE_SUPRESS,
	__SPEEX_PREPROCESS_ECHO_SUPRESS,
	__SPEEX_PREPROCESS_ECHO_SUPRESS_ACTIVE,
	__SPEEX_PREPROCESS_ECHO_STATE,

};


#endif /* PLUGINDEFINITIONS_H_ */

